### ISSUE TITLE
Is it possible to download the pre-made image?

### ISSUE THREAD

**Issue by polhaghverdian** [Mithrandil/PixieLive-build-system#1]

**Comment by Mithrandil** [comment]
Releases 1 and 4 can now be downloaded here:

https://pixielive.org/index.php?post/2010/08/23/FirstRelease
https://pixielive.org/index.php?post/2013/10/21/PixieLive4-Released

**Comment by polhaghverdian** [comment]
@Mithrandil Thank you very much!
